version: "3.3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
    - "27017:27017"
    networks:
    - network
  jenkins:
    image: jenkins/jenkins:lts
    build: ./jenkins/.
    container_name: jenkins
    ports:
    - "8080:8080"
    - "50000:50000"
    # volumes:
    #   - /home/jenkins:/var/jenkins_home
    networks:
    - network
networks:
  network:
