version: "3.3"
services:
  jenkins:
    image: jenkins/jenkins:2.233
    container_name: jenkins
    build: ./jenkins/.
    ports:
    - "8080:8080"
    - "50000:50000"
    # volumes:
    #   - /tmp/jenkins:/var/jenkins_home
    # networks:
    # - network
  git:
    container_name: git
    restart: on-failure
    build: ./git/.
    environment:
      - PASSWORD=${GIT_PASSWORD}
  ip:
    container_name: ip
    restart: on-failure
    build: ./ip/.
  set_router:
    container_name: set_router
    restart: on-failure
    build: ./router53/.
    environment:
    - ROUTE53_URL=https://t5018nbtn5.execute-api.eu-central-1.amazonaws.com/final/DNS_setting_lambda
    - ROUTE53_PASSWORD=${ROUTE53_PASSWORD}
  camera:
    container_name: camera
    restart: on-failure
    build: ./camera/.
    ports:
    - "8400:3000"
    volumes:
    - type: bind
      source: /media/miso/ExtDriver/eramos
      target: /root/node/eramos
  file:
    container_name: file
    restart: on-failure
    build: ./file/.
    ports:
    - "8500:3000"
    volumes:
    - type: bind
      source: /media/miso/ExtDriver/eramosFiles
      target: /scr/files/
  ftp:
    container_name: ftp
    restart: on-failure
    build: ./ftp/.
    ports:
    - "2121:21"
    volumes:
    - type: bind
      source: /media/miso/ExtDriver/eramos
      target: /root/data
  s3:
    container_name: s3
    restart: on-failure
    build: ./s3/.
    environment:
    - ACCESS_KEY=${ACCESS_KEY}
    - SECRET_KEY=${SECRET_KEY}
    - BUCKETS_NAME=${BUCKETS_NAME}
    volumes:
    - type: bind
      source: /media/miso/ExtDriver
      target: /usr/src/app/data
networks:
  network:
