version: "3.3"
services:
  jenkins:
    image: jenkins/jenkins:2.233
    container_name: jenkins
    build: ./jenkins/.
    ports:
    - "8080:8080"
    - "50000:50000"
    # volumes:
    #   - /tmp/jenkins:/var/jenkins_home
    # networks:
    # - network
  git:
    container_name: git
    restart: on-failure
    build: ./git/.
    environment:
      - PASSWORD=${GIT_PASSWORD}
  ip:
    container_name: ip
    restart: on-failure
    build: ./ip/.
  set_router:
    container_name: set_router
    restart: on-failure
    build: ./router53/.
    environment:
    - ROUTE53_URL=https://t5018nbtn5.execute-api.eu-central-1.amazonaws.com/final/DNS_setting_lambda
    - ROUTE53_PASSWORD=${ROUTE53_PASSWORD}
networks:
  network:
