version: "3.3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
    - "27017:27017"
    volumes:
    - /media/ubuntu/db1:/data/db
  git:
    container_name: git
    restart: on-failure
    build: ./git/.
    environment:
      - PASSWORD=${GIT_PASSWORD}
  ip:
    container_name: ip
    restart: on-failure
    build: ./ip/.
  set_router:
    container_name: set_router
    restart: on-failure
    build: ./router53/.
    environment:
    - ROUTE53_URL=${ROUTE53_URL}
    - ROUTE53_PASSWORD=${ROUTE53_PASSWORD}
  camera:
    container_name: camera
    restart: on-failure
    build: ./camera/.
    ports:
    - "8400:3000"
    volumes:
    - type: bind
      source: /media/ubuntu/ExtDriver/eramos
      target: /root/node/eramos
  file:
    container_name: file
    restart: on-failure
    build: ./file/.
    ports:
    - "8500:3000"
    volumes:
    - type: bind
      source: /media/ubuntu/ExtDriver/eramosFiles
      target: /scr/files/
  # s3:
  #   container_name: s3
  #   restart: on-failure
  #   build: ./s3/.
  #   environment:
  #   - ACCESS_KEY=${ACCESS_KEY}
  #   - SECRET_KEY=${SECRET_KEY}
  #   - BUCKETS_NAME=${BUCKETS_NAME}
  #   volumes:
  #   - type: bind
  #     source: /media/ubuntu/ExtDriver
  #     target: /usr/src/app/data
  Send_files:
    container_name: Send_files
    restart: on-failure
    build: ./Send_files/.
    environment:
    - API_URL=${API_URL}
    - API_KEY=${API_KEY}
    volumes:
    - type: bind
      source: /media/ubuntu/ExtDriver
      target: /usr/src/app/data
networks:
  network:
  # ftp:
  #   container_name: ftp
  #   restart: on-failure
  #   build: ./ftp/.
  #   ports:
  #   - "2121:21"
  #   volumes:
  #   - type: bind
  #     source: /media/ubuntu/ExtDriver/eramos
  #     target: /root/data
  # jenkins:
  #   image: jenkins/jenkins:2.233
  #   container_name: jenkins
  #   build: ./jenkins/.
  #   ports:
  #   - "8080:8080"
  #   - "50000:50000"
    # volumes:
    #   - /tmp/jenkins:/var/jenkins_home
